server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/elo_db

app.cookie.secure=false

jwt.secret=ZWxvLWFwaS1jaGF2ZS1zZWNyZXRhLWRlLWRlc2Vudm9sdmltZW50by0yMDI2
jwt.expiration-ms=86400000
